spring.datasource.url = jdbc:postgresql://localhost:5432/postgres
spring.datasource.username = postgres
spring.datasource.password = omniverse
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

file.upload.dir = C:/uploads

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

# Exchange
rabbitmq.exchange.name=notification.exchange

# Queues
rabbitmq.queue.email=email.queue
rabbitmq.queue.sms=sms.queue
rabbitmq.queue.log=log.queue

# DLQ
rabbitmq.exchange.dlx=dlx.exchange
rabbitmq.queue.dlq=dead.letter.queue

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=premiumserbest@gmail.com
spring.mail.password=vfjj asds gkkz ykrd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=USc8c3d9a498898a9618c6852377b90666
twilio.auth.token=0732ea94aecdd3fb9f3758c1e98a778e
twilio.phone.number=+16627279453